name = "mov-mint"
compatibility_date = "2023-10-30"

[build]
command = "npm run build"

# Specify the assets directory for static site
[site]
bucket = "./out"

# Specify the entry point for the worker
main = "_worker.js"
